changelog:
  exclude:
    labels:
      - docs
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Maintenance
      labels:
        - chore
        - refactor
        - deps
